### ISSUE TITLE
Change README example

### ISSUE THREAD

**Issue by adriendomoison** [HsuanXyz/ionic2-transparent-bar#1]
Hello,

I was wondering if you were considering changing the running GIF on the README, I would love to use your library but considering that I might have to go back several time to the repo, present it to collegues or event put link to that repo in documents, as long as this GIF is here, I won't be able to use it...

Thanks !

**Comment by hsuanxyz** [comment]
> English is not my native language; please excuse typing errors.
@adriendomoison 
Do you want to delete it or change the content or size.
you mean this image is too large for you ?

**Comment by adriendomoison** [comment]
Hello,
I am talking about the inappropriate picture on the demo GIF in the README :)
Could you redo the GIF (change the content) with a different image? A butterfly would be more appropriate aha
Thanks a lot !

**Comment by hsuanxyz** [comment]
I have changed the GIF, please clear the browser cache

**Comment by adriendomoison** [comment]
You DID put a butterfly! Aha thank you very much, I really appreciate :) :heart:
